image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  IMAGE_DEVL_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_JOB_ID
  IMAGE_PROD_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  registry: quay.io
  image_name: curator-container
  quay_org: samsung_cnct
  robot_account: curator_container_rw
# Create a Gitlab Secret Variable called QUAY_PASSWORD and assign it the value of the Quay robot docker login password.
# DO NOT PASTE THIS PASSWORD HERE.

stages:
  - build
  - test
  - publish

build-branch:
  stage: build
  only:
    - branches
  except:
    - master
  script:
  - docker build -t $IMAGE_DEVL_NAME .
  - docker push $IMAGE_DEVL_NAME

build-master:
  stage: build
  only:
    - master
    - tags
  script:
  - docker build -t $IMAGE_PROD_NAME .
  - docker push $IMAGE_PROD_NAME

# test:
#    stage: test

publish-master:
  stage: publish
  only:
    - master
  script:
  - docker pull $IMAGE_PROD_NAME
  - docker login ${registry} -u ${quay_org}+${robot_account} -p ${QUAY_PASSWORD}
  # Any merge to master (i.e. a successful CI pass) will be tagged and pushed as latest
  - docker tag ${IMAGE_PROD_NAME} ${registry}/${quay_org}/${image_name}:latest
  - docker push ${registry}/${quay_org}/${image_name}:latest

publish-version-tag:
  stage: publish
  only:
    - /v[0-9]+\.[0-9]+(\.[0-9]+[a-z]?)?/
  script:
  - docker pull $IMAGE_PROD_NAME
  - docker login ${registry} -u ${quay_org}+${robot_account} -p ${QUAY_PASSWORD}
  # A tag push to master will be pushed to Quay with that tag
  - docker tag ${IMAGE_PROD_NAME} ${registry}/${quay_org}/${image_name}:$CI_COMMIT_TAG
  - docker push ${registry}/${quay_org}/${image_name}:$CI_COMMIT_TAG

  #test commit